networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://molodost:b26032e8527d@db:5432/molodost
    depends_on:
      - db
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: molodost
      POSTGRES_PASSWORD: b26032e8527d
      POSTGRES_DB: molodost
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres_data:
